# warning: do not use *tuple* in yaml file
# Note that an empty space is None, but None is "None"

BASE:
    MODEL_ID: COLOR_TRANSFER
    USE_MULTI_GPU: False
    SAME_PROB: 0
    BATCH_PER_GPU: 4
    MAX_STEP: 400000
    SAVE_ROOT: train_results
    PACKAGES_PATH: /home/compu/FaceSwapping/packages
    DO_VALID: False
    DO_TEST: False
    IMG_SIZE: 512

# weight of loss
LOSS:
    W_ADV: 1
    W_VGG:
    W_RECON: 0
    W_CYCLE: 20
    W_FEAT: 10

CYCLE:
    LOSS: 10
    IMAGE: 200
    VALID: 500
    TEST: 500
    CKPT: 2500

CKPT:
    # ckpt path
    # load checkpoints from ./train_result/{ckpt_id}/ckpt/G_{ckpt_step}.pt
    # if ckpt_id is empty, load G_latest.pt and D_latest.pt
    TURN_ON: False
    ID: 
    STEP:

WANDB:
    TURN_ON: TRUE
    ALERT_THRES: 1000


OPTIMIZER:
    TYPE: Adam # [Ranger, Adam]
    BETA: [0.9, 0.999] # default: Adam (0.9, 0.999) / Ranger (0.95, 0.999)
    LR_G: 0.0001
    LR_D: 0.00001

DATASET:
    TRAIN: [
        '../dataset/CelebHQ',
        '../dataset/ffhq16k'
        ]

    VALID: [
        '../dataset/CelebHQ',
        '../dataset/ffhq16k'
        ]

    TEST: ./assets/k-celeb
