# warning: do not use *tuple* in yaml file
# Note that an empty space is None, but None is "None"

BASE:
    MODEL_ID: COLOR_TRANSFER
    USE_MULTI_GPU: False
    SAME_PROB: 0
    BATCH_PER_GPU: 2
    MAX_STEP: 400000
    SAVE_ROOT: train_results
    PACKAGES_PATH:
    DO_TRAIN: True
    DO_VALID: True
    DO_TEST: False
    IMG_SIZE: 512

# weight of loss
LOSS:
    W_ADV: 1
    W_VGG:
    W_RECON: 0
    W_CYCLE: 20
    W_FEAT: 10
    W_LPIPS: 10

CYCLE:
    LOSS: 10
    IMAGE: 50
    VALID: 50
    TEST: 50
    CKPT: 100

CKPT:
    # ckpt path
    # load checkpoints from ./train_result/{ckpt_id}/ckpt/G_{ckpt_step}.pt
    # if ckpt_id is empty, load G_latest.pt and D_latest.pt
    TURN_ON: False
    ID_NUM: 
    STEP:

WANDB:
    TURN_ON: True
    ALERT_THRES: 1000


OPTIMIZER:
    TYPE: Adam # [Ranger, Adam]
    BETA: [0.0, 0.999] # default: Adam (0.9, 0.999) / Ranger (0.95, 0.999)
    LR_G: 0.0001
    LR_D: 0.00001

DATASET:
    TRAIN_PATH:
        IMAGE:
            - /media/deep3090/hdd/DATASET/k_face/images
        MASK:
            - /media/deep3090/hdd/DATASET/k_face/label

    VAL_SIZE: 10

    TEST_PATH:
        IMAGE:
            - ./assets/images
        MASK:
            - ./assets/labels 
